#!/usr/bin/env python3
"""
Краткие оценки пригодности текстовых моделей для «диалог + ответы на вопросы».

Используется генератором generate.py при построении README.text.md.
Ключ — id модели из API OpenRouter. Если модели нет в словаре,
генератор применяет автоматическую эвристику (default_note).
"""

NOTES = {
    # Anthropic
    "anthropic/claude-opus-5": "Максимальное качество диалога и ответов на сложные вопросы",
    "anthropic/claude-opus-5-fast": "Быстрый Opus 5; то же качество, вдвое дороже",
    "anthropic/claude-opus-4.8": "Сильнейший диалог и агентная работа",
    "anthropic/claude-opus-4.7": "Сильнейший диалог и кодинг",
    "anthropic/claude-opus-4.6": "Сильнейший диалог и агентная работа",
    "anthropic/claude-opus-4.5": "Сильнейший диалог, длинный контекст",
    "anthropic/claude-opus-4.1": "Максимальное качество, дорого",
    "anthropic/claude-opus-4": "Максимальное качество, дорого",
    "anthropic/claude-sonnet-5": "Превосходный диалог, сильнейшие ответы на вопросы",
    "anthropic/claude-sonnet-4.6": "Отличный диалог, агентный фокус",
    "anthropic/claude-sonnet-4.5": "Отличный диалог и ответы",
    "anthropic/claude-sonnet-4": "Отличный диалог и кодинг",
    "anthropic/claude-haiku-4.5": "Быстрый и дешёвый; хороший диалог, надёжные ответы",
    "anthropic/claude-3-haiku": "Быстрый Claude; хороший диалог, знания до 2023",
    "anthropic/claude-fable-5": "Mythos-класс; автономная работа, дорого",
    "~anthropic/claude-sonnet-latest": "Алиас Sonnet; превосходный диалог",
    "~anthropic/claude-haiku-latest": "Алиас Haiku; хороший диалог",
    "~anthropic/claude-opus-latest": "Алиас Opus; максимальное качество",

    # OpenAI
    "openai/gpt-5.6-sol": "Флагман GPT-5.6; топовый диалог и сложные вопросы",
    "openai/gpt-5.6-sol-pro": "Sol с pro-reasoning; топовый диалог",
    "openai/gpt-5.6-terra": "Сбалансированный GPT-5.6; сильный диалог",
    "openai/gpt-5.6-luna": "Бюджетный GPT-5.6; отличный чат и Q&A, оптимален",
    "openai/gpt-5.6-luna-pro": "Luna с pro-reasoning; отличный чат и Q&A",
    "openai/gpt-5.5-pro": "Самая мощная reasoning-модель OpenAI; глубочайшие ответы, дорого",
    "openai/gpt-5.5": "GPT-5.5; отличный диалог и рассуждения",
    "openai/gpt-5.4-pro": "GPT-5.4 Pro; максимальное качество, дорого",
    "openai/gpt-5.4": "GPT-5.4; сильный диалог и рассуждения",
    "openai/gpt-5.4-mini": "GPT-5.4 Mini; хороший диалог и Q&A",
    "openai/gpt-5.4-nano": "GPT-5.4 Nano; быстрый, простые диалоги",
    "openai/gpt-5.2": "GPT-5.2; сильный диалог и рассуждения",
    "openai/gpt-5.2-chat": "Быстрый GPT-5.2; хороший диалог",
    "openai/gpt-5.2-pro": "Максимальный GPT-5.2; очень дорого",
    "openai/gpt-5.1": "GPT-5.1; сильный диалог, естественный стиль",
    "openai/gpt-5": "GPT-5; сильный диалог и рассуждения",
    "openai/gpt-5-pro": "GPT-5 Pro; максимальное качество, дорого",
    "openai/gpt-5-mini": "Компактный GPT-5; хороший диалог и лёгкие рассуждения",
    "openai/gpt-5-nano": "Самый быстрый GPT-5; простые диалоги",
    "openai/gpt-4.1": "GPT-4.1; сильный диалог и фактические ответы",
    "openai/gpt-4.1-mini": "GPT-4.1 Mini; хороший диалог, сильные ответы",
    "openai/gpt-4.1-nano": "GPT-4.1 Nano; простые диалоги",
    "openai/gpt-4o": "Проверенный GPT-4o; отличный диалог и Q&A",
    "openai/gpt-4o-2024-11-20": "GPT-4o; отличный диалог, лучшее письмо",
    "openai/gpt-4o-mini": "Бюджетный GPT-4o; хороший диалог и Q&A",
    "openai/gpt-4-turbo": "GPT-4 Turbo; хороший диалог, знания до 2023",
    "openai/o3": "Мощный reasoning; глубокие ответы, диалог сдержанный",
    "openai/o3-pro": "Топовый reasoning; максимально глубокие ответы",
    "openai/o3-mini": "Reasoning о3-mini; хорош в STEM, диалог суше",
    "openai/o3-mini-high": "Reasoning high; глубокие рассуждения",
    "openai/o4-mini": "Reasoning o4-mini; хорош в STEM и кодинге",
    "openai/o4-mini-high": "Reasoning high; глубокие рассуждения",
    "openai/o1": "Reasoning o1; глубокие рассуждения, сдержанный диалог",
    "openai/o1-pro": "Максимальный reasoning; очень дорого",
    "openai/gpt-chat-latest": "Алиас ChatGPT; хороший диалог",
    "~openai/gpt-latest": "Алиас GPT; сильный диалог",
    "~openai/gpt-mini-latest": "Алиас GPT Mini; хороший диалог",
    "openai/gpt-oss-120b": "Открытая 117B; хороший диалог, сильные ответы",
    "openai/gpt-oss-20b": "Открытая OpenAI; неплохой диалог, средние ответы",
    "openai/gpt-oss-20b:free": "Открытая OpenAI; неплохой диалог, средние ответы",

    # Google / Gemini
    "google/gemini-3.7-flash": "Gemini 3.7 Flash; отличный диалог и Q&A, оптимальный выбор",
    "google/gemini-3.6-flash": "Gemini 3.6 Flash; отличный универсальный диалог",
    "google/gemini-3.5-flash": "Gemini 3.5 Flash; сильный диалог и Q&A",
    "google/gemini-3.5-flash-lite": "Лёгкая Gemini; нормальный диалог",
    "google/gemini-3.1-flash-lite": "Лёгкая; нормальный диалог, лёгкие вопросы",
    "google/gemini-3-flash-preview": "Предпросмотр; хороший диалог, быстрый",
    "google/gemini-3.1-pro-preview": "Pro-предпросмотр; сильный диалог и рассуждения",
    "google/gemini-2.5-pro": "Прошлый флагман; сильный диалог и рассуждения",
    "google/gemini-2.5-flash": "Прошлый workhorse; хороший диалог и рассуждения",
    "google/gemini-2.5-flash-lite": "Лёгкая сверхбыстрая; нормальный диалог, лёгкие Q&A",
    "google/gemma-4-31b-it": "Открытая 31B; живой диалог, достойные ответы",
    "google/gemma-4-26b-a4b-it": "Эффективная MoE; среднее качество",
    "google/gemma-3-27b-it": "Открытая 27B; приятный диалог, средние ответы",
    "google/gemma-3-12b-it": "Открытая 12B; нормальный диалог",
    "google/gemma-3-4b-it": "Открытая 4B; простые диалоги",
    "google/gemma-3n-e4b-it": "Мобильная 4B; очень простые диалоги",
    "~google/gemini-flash-latest": "Алиас актуального Flash; отличный диалог",
    "~google/gemini-pro-latest": "Алиас Pro; сильный диалог и рассуждения",

    # DeepSeek
    "deepseek/deepseek-v4-flash-0731": "Актуальный Flash; отличный диалог и Q&A, лучшее соотношение цена/качество",
    "deepseek/deepseek-v4-flash": "Быстрая V4 Flash; сильный диалог и рассуждения",
    "~deepseek/deepseek-v4-flash-latest": "Алиас V4 Flash; отличный диалог",
    "deepseek/deepseek-v4-pro": "Мощная V4 Pro; отличный диалог и рассуждения",
    "deepseek/deepseek-v4-pro-0813": "GA V4 Pro; сильный универсал",
    "deepseek/deepseek-r1-0528": "Знаменитая R1; превосходные рассуждения, формальный диалог",
    "deepseek/deepseek-r1": "R1; сильные рассуждения, сдержанный диалог",
    "deepseek/deepseek-r1-distill-llama-70b": "Дистилляция R1; средний диалог",
    "deepseek/deepseek-v3.2": "V3.2; сильный диалог и Q&A",
    "deepseek/deepseek-chat-v3.1": "Гибридная; отличный диалог и рассуждения",
    "deepseek/deepseek-chat-v3-0324": "Улучшенный V3; хороший диалог и Q&A",
    "deepseek/deepseek-chat": "Классический V3; надёжный диалог",

    # Qwen
    "qwen/qwen3.8-max": "Qwen3.8 Max; отличный универсальный диалог и Q&A",
    "qwen/qwen3.8-2.4t-a95b": "Гигантская открытая MoE (95B активных); очень сильный диалог",
    "qwen/qwen3.7-max": "Qwen3.7 Max; хороший диалог, офисный фокус",
    "qwen/qwen3.7-plus": "Qwen3.7 Plus; хороший диалог и Q&A",
    "qwen/qwen3.7-flash": "Быстрая Qwen; отличный диалог и Q&A за копейки",
    "qwen/qwen3.6-plus": "Qwen3.6 Plus; хороший диалог и Q&A",
    "qwen/qwen3.6-flash": "Быстрая Qwen3.6; хороший диалог и Q&A",
    "qwen/qwen3.6-max-preview": "Qwen3.6 Max Preview; сильный диалог",
    "qwen/qwen3.5-plus-20260420": "Qwen3.5 Plus; хороший диалог и Q&A",
    "qwen/qwen3-max": "Qwen3 Max; хороший диалог и рассуждения",
    "qwen/qwen3-max-thinking": "Reasoning Qwen3 Max; глубокие рассуждения",
    "qwen/qwen3-235b-a22b": "Крупная MoE; сильные ответы и рассуждения",
    "qwen/qwen3-32b": "Dense 32B; хороший диалог, достойные ответы",
    "qwen/qwen3-30b-a3b-instruct-2507": "Эффективная MoE; хороший диалог и ответы",
    "qwen/qwen3-14b": "Dense 14.8B; нормальный чат, средние ответы",
    "qwen/qwen3-8b": "Компактная; неплохой диалог, лёгкие вопросы",
    "qwen/qwen-plus": "Qwen-Plus; хороший универсальный диалог и Q&A",
    "qwen/qwen2.5-72b-instruct": "Проверенная 72B; хороший диалог, надёжные ответы",
    "qwen/qwen-2.5-7b-instruct": "Компактная; простые диалоги",
    "qwen/qwen3.5-397b-a17b": "Крупная MoE; сильные ответы",
    "qwen/qwen3.5-122b-a10b": "Крупная MoE; хороший диалог и ответы",

    # xAI / Grok
    "x-ai/grok-4.6": "Grok 4.6 флагман; топовый диалог, отличный Q&A",
    "x-ai/grok-4.5": "Grok 4.5; живой диалог, сильные фактические ответы",
    "x-ai/grok-4.3": "Grok 4.3; хороший диалог, высокая фактичность",
    "x-ai/grok-4.20": "Grok 4.20; низкая галлюцинация, строгое следование",
    "~x-ai/grok-latest": "Алиас Grok; топовый диалог",
    "x-ai/grok-build-0.1": "Быстрый кодинг; не для общего диалога",

    # Meta / Llama
    "meta-llama/llama-3.3-70b-instruct": "Проверенная 70B; отличный многоязычный диалог",
    "meta-llama/llama-3.1-70b-instruct": "Надёжная 70B; хороший диалог, сильные ответы",
    "meta-llama/llama-3.1-8b-instruct": "Классика Llama 8B; нормальный диалог, средние ответы",
    "meta-llama/llama-3.2-3b-instruct": "Компактная 3B; простые диалоги",
    "meta-llama/llama-3.2-1b-instruct": "Мини 1B; очень простые диалоги",
    "meta-llama/llama-4-maverick": "Новая Llama 4; средний диалог",
    "meta-llama/llama-4-scout": "Llama 4 Scout; средний диалог",
    "meta-llama/llama-guard-4-12b": "Safety-классификатор; не для диалога",

    # Mistral
    "mistralai/mistral-large-2512": "Mistral Large 3; хороший диалог, сильные ответы",
    "mistralai/mistral-medium-3-5": "Mistral Medium 3.5; хороший диалог, достойные ответы",
    "mistralai/mistral-medium-3": "Mistral Medium 3; приятный диалог",
    "mistralai/mistral-medium-3.1": "Mistral Medium 3.1; приятный диалог",
    "mistralai/mistral-small-2603": "Mistral Small 4; хороший диалог, средние ответы",
    "mistralai/mistral-small-24b-instruct-2501": "Быстрая 24B; живой диалог, адекватные ответы, дёшево",
    "mistralai/mistral-small-3.2-24b-instruct": "Быстрая 24B; хороший диалог, достойные ответы",
    "mistralai/mistral-small-3.1-24b-instruct": "24B; хороший диалог, средние ответы",
    "mistralai/mistral-nemo": "Многоязычная 12B; приятный естественный диалог, хороший Q&A",
    "mistralai/mixtral-8x22b-instruct": "Крупная открытая MoE; хороший диалог",
    "mistralai/codestral-2508": "Кодинг-модель; не для общего диалога",
    "mistralai/mistral-large-2407": "Mistral Large 2; хороший диалог и ответы",
    "mistralai/mistral-large": "Mistral Large 2; хороший диалог и ответы",
    "mistralai/mistral-saba": "Для Ближнего Востока; нишевый диалог",

    # Moonshot / Kimi
    "moonshotai/kimi-k3": "Флагман Kimi; отличный диалог и глубокие рассуждения",
    "moonshotai/kimi-k2.7-code": "Кодинг-модель; для общих вопросов ограниченно",
    "moonshotai/kimi-k2.6": "Kimi K2.6; хороший диалог, длинные задачи",
    "moonshotai/kimi-k2.5": "Kimi K2.5; хороший диалог, визуальный кодинг",
    "moonshotai/kimi-k2-thinking": "Открытый reasoning; хороший диалог, глубокие ответы",
    "moonshotai/kimi-k2-0905": "Kimi K2; хороший диалог и рассуждения",
    "moonshotai/kimi-k2": "Kimi K2; хороший диалог и рассуждения",
    "~moonshotai/kimi-latest": "Алиас Kimi; хороший диалог",

    # Z.ai / GLM
    "z-ai/glm-5.3": "Новейший reasoning GLM; топовый диалог и сложные вопросы",
    "z-ai/glm-5.2": "Флагман GLM 5.2; превосходный диалог, глубокие ответы",
    "z-ai/glm-5.2:free": "Флагман бесплатно — отличный универсальный диалог и Q&A",
    "z-ai/glm-5.2:batch": "GLM 5.2 batch; превосходный диалог",
    "z-ai/glm-5.1": "GLM 5.1; сильный диалог, отличный кодинг",
    "z-ai/glm-5": "Флагман GLM 5; отличный диалог и рассуждения",
    "z-ai/glm-5-turbo": "Быстрый GLM; хороший диалог",
    "z-ai/glm-4.7": "Флагман GLM 4.7; отличный диалог, многошаговые рассуждения",
    "z-ai/glm-4.7-flash": "Быстрая 30B-класс; хороший диалог, хорош для агентов",
    "z-ai/glm-4.6": "GLM 4.6; хороший диалог и рассуждения",
    "z-ai/glm-4.5": "GLM 4.5; хороший диалог, агентный фокус",
    "z-ai/glm-4.5-air": "Лёгкий GLM; нормальный диалог, средние ответы",
    "~z-ai/glm-latest": "Алиас GLM; превосходный диалог",

    # MiniMax
    "minimax/minimax-m3": "MiniMax M3; хороший диалог, длинный контекст",
    "minimax/minimax-m2.7": "MiniMax M2.7; хороший диалог и рассуждения",
    "minimax/minimax-m2.5": "MiniMax M2.5; хороший диалог и ответы",
    "minimax/minimax-m2.1": "MiniMax M2.1; хороший диалог и ответы",
    "minimax/minimax-m2-her": "Специально для диалога/ролеплея; лучший тон разговора",
    "minimax/minimax-m2": "MiniMax M2; хороший диалог и ответы",
    "minimax/minimax-m1": "MiniMax M1; хороший диалог, длинный контекст",
    "minimax/minimax-01": "MiniMax-01; хороший диалог, длинный контекст",

    # Прочие
    "inclusionai/ling-3.0-flash": "Эффективная MoE; средний диалог",
    "inclusionai/ling-2.6-flash": "Мгновенная; быстрый простой чат, низкий интеллект",
    "inclusionai/ling-2.6-1t": "Trillion-параметров; хороший диалог, эффективный",
    "inclusionai/ring-2.6-1t": "Reasoning 1T; глубокие рассуждения",
    "bytedance-seed/seed-2.1-turbo": "Seed 2.1 Turbo; хороший диалог, силён в кодинге",
    "bytedance-seed/seed-2.0-lite": "Seed 2.0 Lite; хороший диалог, средние ответы",
    "bytedance-seed/seed-1.6-flash": "Seed 1.6 Flash; быстрый, средний диалог",
    "nousresearch/hermes-4-405b": "Крупный Hermes 4; сильный диалог и рассуждения",
    "nousresearch/hermes-4-70b": "Гибрид reasoning; хороший диалог, сильные ответы",
    "nousresearch/hermes-3-llama-3.1-405b": "Крупный Hermes 3; сильный диалог и рассуждения",
    "nousresearch/hermes-3-llama-3.1-70b": "Отличный открытый универсал; хороший диалог и ролеплей",
    "amazon/nova-premier-v1": "Nova Premier; хороший диалог и рассуждения",
    "amazon/nova-pro-v1": "Старшая Nova; хороший диалог, достойные ответы",
    "amazon/nova-lite-v1": "Недорогая Nova; нормальный диалог, средние ответы",
    "amazon/nova-micro-v1": "Самая быстрая Nova; простые диалоги и лёгкие вопросы",
    "cohere/command-a": "Cohere Command A; RAG/инструменты, нормальный диалог",
    "cohere/command-r-08-2024": "Cohere Command R; нормальный диалог, RAG-фокус",
    "cohere/command-r7b-12-2024": "Компактная Cohere; средний диалог, RAG-фокус",
    "upstage/solar-pro4": "Дешёвая, длинный контекст; нормальный диалог, средние ответы",
    "upstage/solar-pro-3": "Upstage Solar Pro 3; средний диалог",
    "writer/palmyra-x5": "Корпоративные агенты; нормальный диалог, enterprise-фокус",
    "perplexity/sonar": "Поисковый Q&A с цитатами; лучший для вопросов с поиском",
    "perplexity/sonar-pro": "Расширенный поисковый Q&A; глубокие ответы с источниками",
    "perplexity/sonar-reasoning-pro": "Поиск + reasoning; сильные аналитические ответы",
    "perplexity/sonar-deep-research": "Глубокий поиск; многошаговое исследование",
    "sakana/sakana-namazu": "Японский специалист; диалог на японском отличный",
    "sakana/fugu-ultra": "Мультиагентная система; сильный диалог, дорого",
    "thinkingmachines/inkling": "Открытая MoE; хороший диалог и рассуждения",
    "thinkingmachines/inkling-small": "Открытая MoE; средний диалог",
    "meituan/longcat-2.0": "Meituan; средний диалог, кодинг-фокус",
    "tencent/hy3": "Tencent Hy3; хороший диалог, сильные рассуждения",
    "tencent/hunyuan-a13b-instruct": "Tencent; нормальный диалог, средние ответы",
    "xiaomi/mimo-v2.5-pro": "Xiaomi флагман; хороший диалог и рассуждения",
    "xiaomi/mimo-v2.5": "Xiaomi; хороший диалог, длинный контекст",
    "stepfun/step-3.5-flash": "Эффективная MoE; нормальный диалог, средние ответы",
    "deepcogito/cogito-v2.1-671b": "Открытый 671B; отличные рассуждения, хороший диалог",
    "allenai/olmo-3-32b-think": "Open reasoning; логика сильная, диалог суше",
    "liquid/lfm-2.5-2.6b:free": "Маленькая reasoning-модель; только лёгкие задачи",
    "nvidia/nemotron-3-ultra-550b-a55b:free": "Сильная MoE (55B активных); хорош в рассуждениях",
    "nvidia/nemotron-3-super-120b-a12b": "Сбалансированная; нормальный диалог и Q&A",
    "nvidia/nemotron-3-nano-30b-a3b": "Компактная; простые диалоги",
    "openrouter/free": "Роутер случайных бесплатных моделей — качество непредсказуемо",
    "openrouter/auto": "Роутер по задачам; качество зависит от выбора",
    "openrouter/auto-beta": "Бета-роутер; качество зависит от выбора",
    "openrouter/fusion": "Мультимодельное обсуждение; хороший Q&A",
}


# ---------------------------------------------------------------------------
# Генерация изображений (README.image.md)
# ---------------------------------------------------------------------------
NOTES_IMAGE = {
    "bytedance-seed/seedream-5-0-lite": "Seedream 5 Lite; быстрая генерация, хорошее качество",
    "bytedance-seed/seedream-5-0-pro": "Seedream 5 Pro; высокое качество, точное следование промпту",
    "bytedance-seed/seedream-4.5": "Seedream 4.5; проверенная генерация изображений",
    "x-ai/grok-imagine-image-2.0": "Grok Imagine; фотореалистичные изображения",
    "x-ai/grok-imagine-image-quality": "Grok Imagine Quality; улучшенное качество генерации",
    "qwen/qwen-image-3": "Qwen Image 3; универсальная генерация изображений",
    "qwen/qwen-image-3-pro": "Qwen Image 3 Pro; повышенное качество и детализация",
    "microsoft/mai-image-2.5": "Microsoft MAI Image 2.5; качественная генерация",
    "microsoft/mai-image-2.5-pro": "Microsoft MAI Image 2.5 Pro; топовое качество",
    "krea/krea-2-large": "Krea 2 Large; мощная генерация изображений",
    "krea/krea-2-medium": "Krea 2 Medium; сбалансированная генерация",
    "krea/krea-2-medium-turbo": "Krea 2 Turbo; быстрая генерация",
    "openai/gpt-image-1": "GPT Image 1; флагман генерации OpenAI",
    "openai/gpt-image-1-mini": "GPT Image 1 Mini; быстрая и дешёвая генерация",
    "openai/gpt-image-2": "GPT Image 2; новейшая генерация OpenAI",
    "openai/gpt-5-image": "GPT-5 Image; генерация с точным следованием инструкциям",
    "openai/gpt-5-image-mini": "GPT-5 Image Mini; лёгкая и быстрая генерация",
    "openai/gpt-5.4-image-2": "GPT-5.4 Image 2; актуальная генерация изображений",
    "google/gemini-3.1-flash-image": "Nano Banana 2; отличное качество, редактирование и генерация",
    "google/gemini-3.1-flash-lite-image": "Nano Banana 2 Lite; лёгкая версия",
    "google/gemini-3.1-flash-image-preview": "Nano Banana 2 Preview; предпросмотр",
    "google/gemini-3-pro-image": "Nano Banana Pro; топовое качество изображений",
    "google/gemini-3-pro-image-preview": "Nano Banana Pro Preview; предпросмотр",
    "google/gemini-2.5-flash-image": "Nano Banana (Gemini 2.5); проверенная генерация",
    "recraft/recraft-v3": "Recraft V3; стильная векторная и растровая генерация",
    "recraft/recraft-v4": "Recraft V4; генерация с упором на дизайн",
    "recraft/recraft-v4-pro": "Recraft V4 Pro; расширенные возможности",
    "recraft/recraft-v4-vector": "Recraft V4 Vector; векторная графика",
    "recraft/recraft-v4-pro-vector": "Recraft V4 Pro Vector; продвинутая векторная",
    "recraft/recraft-v4-utility": "Recraft V4 Utility; практичная генерация",
    "recraft/recraft-v4-utility-pro": "Recraft V4 Utility Pro; улучшенная практичная",
    "recraft/recraft-v4.1": "Recraft V4.1; актуальная генерация",
    "recraft/recraft-v4.1-pro": "Recraft V4.1 Pro; расширенные возможности",
    "recraft/recraft-v4.1-vector": "Recraft V4.1 Vector; векторная графика",
    "recraft/recraft-v4.1-pro-vector": "Recraft V4.1 Pro Vector; продвинутая векторная",
    "recraft/recraft-v4.1-utility": "Recraft V4.1 Utility; практичная генерация",
    "recraft/recraft-v4.1-utility-pro": "Recraft V4.1 Utility Pro; улучшенная практичная",
    "sourceful/riverflow-v2-fast": "Riverflow V2 Fast; быстрая генерация",
    "sourceful/riverflow-v2-pro": "Riverflow V2 Pro; высокое качество",
    "sourceful/riverflow-v2.5-fast": "Riverflow V2.5 Fast; быстрая актуальная генерация",
    "sourceful/riverflow-v2.5-pro": "Riverflow V2.5 Pro; высокое качество",
    "black-forest-labs/flux.2-pro": "FLUX.2 Pro; премиальная генерация Black Forest",
    "black-forest-labs/flux.2-max": "FLUX.2 Max; максимальное качество",
    "black-forest-labs/flux.2-flex": "FLUX.2 Flex; гибкая генерация",
    "black-forest-labs/flux.2-klein-4b": "FLUX.2 Klein 4B; компактная и быстрая",
    "openrouter/auto": "Роутер по задачам; выбирает модель автоматически",
    "openrouter/auto-beta": "Бета-роутер; выбирает модель автоматически",
}


# ---------------------------------------------------------------------------
# Эмбеддинги (README.embeddings.md)
# ---------------------------------------------------------------------------
NOTES_EMBEDDINGS = {
    "openai/text-embedding-3-small": "OpenAI text-embedding-3-small; эффективные эмбеддинги",
    "openai/text-embedding-3-large": "OpenAI text-embedding-3-large; максимальная размерность",
    "openai/text-embedding-ada-002": "OpenAI ada-002; классические надёжные эмбеддинги",
    "openai/text-embedding-ada-002:batch": "ada-002 batch; пакетный режим",
    "openai/text-embedding-3-large:batch": "text-embedding-3-large batch; пакетный режим",
    "openai/text-embedding-3-small:batch": "text-embedding-3-small batch; пакетный режим",
    "google/gemini-embedding-001": "Gemini Embedding 001; ранний эмбеддер Google",
    "google/gemini-embedding-2": "Gemini Embedding 2; актуальный эмбеддер Google",
    "google/gemini-embedding-2-preview": "Gemini Embedding 2 Preview; предпросмотр",
    "voyageai/voyage-4": "Voyage 4; универсальные эмбеддинги",
    "voyageai/voyage-4-lite": "Voyage 4 Lite; лёгкие и быстрые",
    "voyageai/voyage-4-large": "Voyage 4 Large; высокое качество",
    "voyageai/voyage-code-4": "Voyage Code 4; эмбеддинги для кода",
    "voyageai/voyage-multimodal-3.5": "Voyage Multimodal 3.5; мультимодальные эмбеддинги",
    "mistralai/mistral-embed-2312": "Mistral Embed; надёжный эмбеддер",
    "mistralai/codestral-embed-2505": "Codestral Embed; эмбеддинги для кода",
    "qwen/qwen3-embedding-8b": "Qwen3 Embedding 8B; крупный эмбеддер",
    "qwen/qwen3-embedding-4b": "Qwen3 Embedding 4B; сбалансированный эмбеддер",
    "nvidia/nemotron-3-embed-1b:free": "Nemotron Embed 1B; компактный эмбеддер",
    "nvidia/llama-nemotron-embed-vl-1b-v2:free": "Llama Nemotron Embed VL; мультимодальный",
    "perplexity/pplx-embed-v1-4b": "Perplexity Embed 4B; поисковые эмбеддинги",
    "perplexity/pplx-embed-v1-0.6b": "Perplexity Embed 0.6B; компактный",
    "thenlper/gte-base": "GTE Base; базовый эмбеддер",
    "thenlper/gte-large": "GTE Large; большой эмбеддер",
    "intfloat/e5-base-v2": "E5 Base V2; текстовые эмбеддинги",
    "intfloat/e5-large-v2": "E5 Large V2; качественные эмбеддинги",
    "intfloat/multilingual-e5-large": "Multilingual E5; многоязычные эмбеддинги",
    "sentence-transformers/paraphrase-minilm-l6-v2": "MiniLM; компактные эмбеддинги для схожести",
    "sentence-transformers/all-minilm-l6-v2": "all-MiniLM-L6; компактные универсальные",
    "sentence-transformers/all-minilm-l12-v2": "all-MiniLM-L12; увеличенная версия",
    "sentence-transformers/all-mpnet-base-v2": "all-MPNet-base; качественные универсальные",
    "sentence-transformers/multi-qa-mpnet-base-dot-v1": "multi-QA MPNet; для вопросно-ответных систем",
    "baai/bge-base-en-v1.5": "BGE Base EN; английские эмбеддинги",
    "baai/bge-large-en-v1.5": "BGE Large EN; качественные английские",
    "baai/bge-m3": "BGE M3; многоязычный мультигранулярный",
    "liquid/lfm-2.5-embedding-350m:free": "LFM Embedding 350M; компактный эмбеддер",
}


# ---------------------------------------------------------------------------
# Генерация видео (README.video.md)
# ---------------------------------------------------------------------------
NOTES_VIDEO = {
    "openai/sora-2-pro": "Sora 2 Pro; флагман генерации видео OpenAI",
    "google/veo-3.1": "Veo 3.1; топовая генерация видео Google",
    "google/veo-3.1-fast": "Veo 3.1 Fast; быстрая генерация",
    "google/veo-3.1-lite": "Veo 3.1 Lite; лёгкая версия",
    "runway/gen-4.5": "Runway Gen-4.5; профессиональная генерация",
    "runway/aleph-2": "Runway Aleph-2; актуальная генерация Runway",
    "minimax/hailuo-3": "Hailuo 3; высокое качество видео",
    "minimax/hailuo-2.3": "Hailuo 2.3; проверенная генерация",
    "black-forest-labs/flux-3-video": "FLUX 3 Video; генерация видео Black Forest",
    "black-forest-labs/flux-video-upscale": "FLUX Video Upscale; повышение разрешения видео",
    "bytedance/seedance-2.0": "Seedance 2.0; генерация видео ByteDance",
    "bytedance/seedance-2.0-fast": "Seedance 2.0 Fast; быстрая версия",
    "bytedance/seedance-2.0-mini": "Seedance 2.0 Mini; компактная версия",
    "bytedance/seedance-2.5": "Seedance 2.5; актуальная генерация",
    "bytedance/seedance-1-5-pro": "Seedance 1.5 Pro; проверенная генерация",
    "alibaba/wan-2.6": "Wan 2.6; генерация видео Alibaba",
    "alibaba/wan-2.7": "Wan 2.7; актуальная генерация Alibaba",
    "alibaba/happyhorse-1.0": "HappyHorse 1.0; генерация видео",
    "alibaba/happyhorse-1.1": "HappyHorse 1.1; обновлённая версия",
    "kwaivgi/kling-v3.0-pro": "Kling 3.0 Pro; качественная генерация",
    "kwaivgi/kling-v3.0-std": "Kling 3.0 Std; стандартная версия",
    "kwaivgi/kling-video-o1": "Kling Video O1; реалистичная генерация",
    "x-ai/grok-imagine-video": "Grok Imagine Video; генерация видео xAI",
    "x-ai/grok-imagine-video-1.5": "Grok Imagine Video 1.5; обновлённая версия",
}


# ---------------------------------------------------------------------------
# Генерация музыки (README.audio.md)
# ---------------------------------------------------------------------------
NOTES_AUDIO = {
    "google/lyria-3-pro-preview": "Lyria 3 Pro; генерация музыки высокого качества",
    "google/lyria-3-clip-preview": "Lyria 3 Clip; музыкальные фрагменты",
    "openai/gpt-audio": "GPT Audio; голосовой диалог и аудио",
    "openai/gpt-audio-mini": "GPT Audio Mini; лёгкий голосовой диалог",
}


# ---------------------------------------------------------------------------
# Реранкинг (README.rerank.md)
# ---------------------------------------------------------------------------
NOTES_RERANK = {
    "cohere/rerank-v3.5": "Cohere Rerank 3.5; реранкинг документов",
    "cohere/rerank-4-pro": "Cohere Rerank 4 Pro; высокое качество",
    "cohere/rerank-4-fast": "Cohere Rerank 4 Fast; быстрый реранкинг",
    "voyageai/rerank-2.5": "Voyage Rerank 2.5; точный реранкинг",
    "voyageai/rerank-2.5-lite": "Voyage Rerank 2.5 Lite; лёгкий и быстрый",
    "qwen/qwen3-reranker-8b": "Qwen3 Reranker 8B; открытый реранкер",
    "nvidia/llama-nemotron-rerank-vl-1b-v2:free": "Llama Nemotron Rerank VL; мультимодальный реранкер",
}


# ---------------------------------------------------------------------------
# Синтез речи / TTS (README.speech.md)
# ---------------------------------------------------------------------------
NOTES_SPEECH = {
    "hexgrad/kokoro-82m": "Kokoro 82M; очень дешёвый и быстрый TTS",
    "fish-audio/s1": "Fish S1; качественный синтез речи",
    "fish-audio/s2-pro": "Fish S2 Pro; естественная речь",
    "fish-audio/s2.1-pro": "Fish S2.1 Pro; актуальный синтез речи",
    "fish-audio/s2.1-pro-free:free": "Fish S2.1 Pro free; бесплатная версия",
    "deepgram/flux-tts:free": "Deepgram Flux TTS; бесплатный синтез",
    "deepgram/aura-2": "Deepgram Aura 2; естественные голоса",
    "microsoft/mai-voice-2": "Microsoft MAI Voice 2; качественный TTS",
    "microsoft/mai-voice-2-flash": "Microsoft MAI Voice 2 Flash; быстрый TTS",
    "qwen/qwen-audio-3.0-tts-flash": "Qwen Audio TTS Flash; быстрый синтез",
    "qwen/qwen-audio-3.0-tts-plus": "Qwen Audio TTS Plus; качественный синтез",
    "minimax/speech-2.8-hd": "MiniMax Speech 2.8 HD; высокое качество",
    "minimax/speech-2.8-turbo": "MiniMax Speech 2.8 Turbo; быстрый синтез",
    "x-ai/grok-voice-tts-1.0": "Grok Voice TTS; синтез речи xAI",
    "google/gemini-3.1-flash-tts-preview": "Gemini Flash TTS; синтез речи Google",
    "canopylabs/orpheus-3b-0.1-ft": "Orpheus 3B; эмоциональный синтез",
    "sesame/csm-1b": "CSM 1B; разговорный синтез речи",
    "mistralai/voxtral-mini-tts-2603": "Voxtral Mini TTS; компактный синтез",
}


# ---------------------------------------------------------------------------
# Транскрипция / STT (README.transcription.md)
# ---------------------------------------------------------------------------
NOTES_TRANSCRIPTION = {
    "openai/whisper-large-v3": "Whisper Large V3; эталон распознавания речи",
    "openai/whisper-large-v3-turbo": "Whisper Large V3 Turbo; быстрая версия",
    "openai/whisper-1": "Whisper-1; классическое распознавание",
    "openai/gpt-transcribe": "GPT Transcribe; мощная транскрипция",
    "openai/gpt-4o-transcribe": "GPT-4o Transcribe; транскрипция GPT-4o",
    "openai/gpt-4o-mini-transcribe": "GPT-4o-mini Transcribe; компактная транскрипция",
    "deepgram/nova-3": "Deepgram Nova 3; быстрая точная транскрипция",
    "google/chirp-3": "Google Chirp 3; распознавание речи",
    "nvidia/parakeet-tdt-0.6b-v3": "Parakeet TDT 0.6B; компактный ASR",
    "nvidia/nemotron-3.5-asr-streaming-multilingual-0.6b": "Nemotron ASR; многоязычное распознавание",
    "mistralai/voxtral-mini-3b-2507": "Voxtral Mini 3B; компактный STT",
    "mistralai/voxtral-mini-transcribe": "Voxtral Mini Transcribe; транскрипция",
    "mistralai/voxtral-small-24b-2507-stt": "Voxtral Small; распознавание речи",
    "qwen/qwen3-asr-0.6b": "Qwen3 ASR 0.6B; компактный ASR",
    "qwen/qwen3-asr-1.7b": "Qwen3 ASR 1.7B; ASR среднего размера",
    "qwen/qwen3-asr-flash-2026-02-10": "Qwen3 ASR Flash; быстрый ASR",
    "fish-audio/transcribe-1": "Fish Transcribe; транскрипция",
    "x-ai/grok-stt-1.0": "Grok STT; распознавание речи xAI",
    "microsoft/mai-transcribe-1.5": "Microsoft MAI Transcribe; качественная транскрипция",
}